name: CI Pipeline

on:
  push:
    branches:
      - main  # Or the default branch you're working with (e.g., master)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: List the contents of the current directory before build
      - name: List current directory before build
        run: |
          echo "Listing contents of the current directory:"
          ls -alh

      # Step 5: Build the Vite app
      - name: Build Vite app
        run: npm run build

      # Step 6: List the contents of the build output directory (dist)
      - name: Check build directory
        run: |
          echo "Listing contents of the dist directory:"
          ls -alh ./dist

      # Step 7: Verify if the dist folder exists
      - name: Verify dist directory exists
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build failed: dist directory is missing."
            exit 1
          else
            echo "Build succeeded: dist directory found."
          fi
